FROM node:20-alpine

WORKDIR /app

# Installation des dépendances globales
RUN npm install -g @angular/cli

# Copie des fichiers de configuration
COPY package*.json ./
COPY angular.json tsconfig*.json ./

# Installation des dépendances du projet
RUN npm install

# Copie du code source
COPY . .

# Exposition du port de développement
EXPOSE 4200

# Commande pour lancer le serveur de développement
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "500"]
